version: '3.7'

services:
  web:
    image: nginx:alpine
    container_name: nginx
    ports: 
      - "80:80"
      - "3000:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    depends_on: 
      - php

  php:
    build: docker/php
    restart: always
    container_name: php
    volumes:
      - .:/var/www/html
    environment: 
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - docker=true
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_port=9001 remote_enable=1
    depends_on: 
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mariadb/server:10.3
    container_name: mariadb
    command: 'mysqld --innodb-flush-method=fsync' # fix un bug à l'initialisation
    restart: always
    env_file:
      - ".env"
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_PORT=${MARIADB_PORT}
      - MARIADB_INITDB_SKIP_TZINFO="yes" # fix un bug à l'initialisation
    ports: 
      - "8989:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:cached # persite la bdd en local
      - ./docker/sql/init.sql:/docker-entrypoint-initdb.d/zz-init.sql # execute les scripts sql par ordre alphabetique